# Generated by Django 3.2 on 2022-02-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=64)),
                ('employee_code', models.IntegerField(max_length=64, unique=True)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=16)),
                ('no_of_leaves', models.IntegerField()),
                ('pf_number', models.CharField(blank=True, max_length=100)),
                ('fixed_anual_ctc', models.FloatField()),
                ('balance_leaves', models.IntegerField()),
                ('monthly_ctc', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salaryslip.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salaryslip.designation')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_breakup', models.TextField()),
                ('salary_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salaryslip.employee')),
            ],
        ),
    ]
