# Generated by Django 3.2 on 2022-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='balance_leaves',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fixed_anual_ctc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_ctc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='no_of_leaves',
            field=models.IntegerField(default=21),
        ),
    ]
