# Generated by Django 3.2 on 2022-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0002_auto_20220217_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='balance_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fixed_anual_ctc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_ctc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
