# Generated by Django 3.2 on 2022-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0003_auto_20220217_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_breakup',
            field=models.JSONField(default={}, max_length=2000),
        ),
        migrations.DeleteModel(
            name='EmployeeSlip',
        ),
    ]
