# Generated by Django 3.2.11 on 2022-02-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryslip', '0004_auto_20220217_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(unique=True),
        ),
    ]
